INSERT INTO Table_Money (ID, USER_BALANCE, USER_ID) VALUES (1, 10, 1);
INSERT INTO Table_Money (ID, USER_BALANCE, USER_ID) VALUES (2, 7, 2);
INSERT INTO Table_Money (ID, USER_BALANCE, USER_ID) VALUES (3, 0, 3);